### PR TITLE
Improve MP4 mime detection

### PR DESCRIPTION
**Pull request by Kagami**
Not sure this is the best fix, I don't know about MP4 container much.

I commited problem file so you can decide by yourself.

### CODE REVIEW

**Comment by bakape** [comment]
I'll need to look into what excatly this fixes. MP4 is a very dumb and obfuscated format.

**Comment by bakape** [comment]
I see. Looks like this is another dumb mp4 offshoot format https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP . Probably would be more reliable to pass to ffmpeg (as a last resort) for detection, instead of special-casing detection of this and any other "kind of MP4 but not really" container formats. Thoughts?

**Comment by Kagami** [comment]
I'm not a fan of ffmpeg detect because of issue described in #7. I think it would be better if we do unreilable mime checks but pass exact container/decoder to ffmpeg. That way if we chose the wrong format ffmpeg will fail anyway.

Another option is to limit allowed formats in ffmpeg. I think it should be possible with `register*`-like functions? Seems like currently all possible formats are accepted while thumbnailer supports only most basic ones. Also we won't need mime sniff in that case: we can just pass everything to ffmpeg. Maybe still useful in order to fail fast on bad files passed by users though.

One more option is to run thumbnailer process separately from application inside e.g. container with disabled networking and sandboxed filesystem. This is good as last resort defense, but in general thumbnailer shouldn't do network requests. There was similar security vulnerability with ImageMagick recently btw. It accepted too many obscrube formats and some of them allowed code execution with specially constructed files. ffmpeg's issue is very similar: it tries to parse tons of possible formats resulting in potentially bad decisions from security point of view.

**Comment by bakape** [comment]
>Maybe still useful in order to fail fast on bad files passed by users though.

That would complicate the ability of library users detect formats without performing thumbnailing. 

Fair points otherwise.

**Comment by Kagami** [comment]
What option (relaxed mimes + pass exact formats/decoders to ffmpeg vs detect everything with ffmpeg) do you like more? I will try to implement it if I have time.

**Comment by bakape** [comment]
Detecting everything with ffmpeg is not an option, as that would break the extension APIs we have now:
https://godoc.org/github.com/bakape/thumbnailer#RegisterMatcher
https://godoc.org/github.com/bakape/thumbnailer#RegisterProcessor

**Comment by Kagami** [comment]
>Matcher takes up to the first 512 bytes of a file and returns the MIME type
Hm, that won't work probably, yeah.
Though that mime check is unreilable anyway, you need to process file fully in order to be sure that it's really valid.

**Comment by bakape** [comment]
>you need to process file fully in order to be sure that it's really valid.

Which is quite expensive, if you just want to detect the MIME type.

**Pull request merged**
