### PR TITLE
Add support for WebMs with transparency

### PR DESCRIPTION
**Pull request by Kagami**
This also fixes a bunch of bugs:

* Incorrect behavior of hasTransparency()
* Corrupted colors of WebM previes with odd dimensions
* Lack of support additional WebM pixel formats (should now work with
  4:2:2, 4:4:4, etc, maybe even high bitdepth, not tested)

### CODE REVIEW

**Comment by bakape** [comment]
Thanks for the fixes! 

Everything seems fine, except TestWebmAlpha is failing for me. `alpha.webm` does not seem to have transparent pixels. Did you perhaps simply copy the wrong file into `testdata`?

**Comment by Kagami** [comment]
What's your version of ffmpeg? Seems like it requires at least 3.2: https://github.com/FFmpeg/FFmpeg/commit/134fe28981cd94206cf4dcfd468ccc1b76391980

**Comment by bakape** [comment]
3.0. I'll compile 3.2 and test later today. Will need to bump up the version requirement, I guess.

**Comment by Kagami** [comment]
Well, it's not mandatory, sort of bonus.

**Comment by bakape** [comment]
Yeah, I guess.

**Pull request merged**
